[project]
name = "ui"
version = "0.1.0"
description = "Streamlit powered UI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.44.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
    "watchdog>=6.0.0",
]
